FROM python:3.9-slim-buster
WORKDIR ./app
RUN pip install --upgrade pip
COPY ./req_back.txt /app/req_back.txt
RUN pip install --no-cache-dir --upgrade -r /app/req_back.txt
COPY backend.py /app/backend.py
COPY /utils/ /app/utils/
COPY ./runners/backend.sh ./app/backend.sh

RUN chmod +x ./app/backend.sh
EXPOSE 8001