FROM python:3.9-slim-buster
WORKDIR /app
RUN pip install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY backend.py /app/backend.py
EXPOSE 8001
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8001"]