FROM python:3.9-slim-buster
WORKDIR ./app
RUN pip install --upgrade pip
COPY ./requirements.txt ./app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./app/requirements.txt
COPY ./app.py ./app/app.py
COPY ./runners/frontend.sh ./app/frontend.sh
RUN chmod +x ./app/frontend.sh
EXPOSE 8501



